
export const DOMAINS = {
    gnc: 'https://www.gnc.com/check-order',
    rejuvacare: 'https://www.rejuvacare.com/pages/tracking',
    happymammoth: 'https://happymammoth.com/pages/tracking',
    mengotomars: 'https://mengotomars.com/pages/help-center',
    froyaorganics: 'https://froyaorganics.com/pages/order-tracking',
    honehealth: 'https://help.honehealth.com/hc/en-us/articles/31264655436311-How-to-Track-Your-Medication-Order',
    luxeresearchlab: 'https://luxeresearchlab.com/apps/track-order',
    buckedup: 'https://www.buckedup.com/customer/orders/find',
    olavita: 'https://olavitaskin.com/apps/parcelpanel?',
    alphalion: 'https://alphalion.aftership.com/',
    // New brands (13-40)
    musclefood: 'https://www.musclefood.com',
    primalking: 'https://primalviking.com',
    innosupps: 'https://www.innosupps.com/pages/track-my-order',
    ploise: 'https://ploise.com/apps/track123',
    equipfoods: 'https://www.equipfoods.com/pages/tracking',
    ancestralsupplements: 'https://ancestralsupplements.com/pages/faq',
    myoro: 'https://myoro.co/apps/17TRACK',
    fieracosmetic: 'https://fieracosmetics.com/pages/tracking-page',
    pendulum: 'https://pendulumlife.com/account/login',
    thebbco: 'https://thebbco.com/pages/track-your-order',
    norseorganics: 'https://norseorganics.co',
    balmbare: 'https://balmbare.com/apps/parcelpanel',
    truvani: 'https://shop.truvani.com',
    trueprotein: 'https://www.trueprotein.com.au/pages/contact-us',
    lonvera: 'https://lonvera.com',
    rejuvia: 'https://www.rejuvia.co',
    zenith: 'https://zenithlabs.com/contact-us/',
    rejuveen: 'https://rejuveen.com/pages/tracking',
    trynomend: 'https://trynomend.com/pages/tracking',
    welleco: 'https://www.welleco.com',
    trysaphire: 'https://trysaphire.com/apps/track123',
    omnicreatine: 'https://omnicreatine.com',
    spnutrition: 'https://snutritionusa.com',
    zenther: 'https://www.zenther.com',
    mivourr: 'https://mivourr.com/apps/track-your-order',
    martinclinic: 'https://martinclinic.com',
    blymeskinsystems: 'https://blymeskinsystems.com/apps/parcelpanel',
    soovera: 'https://soovera.com/apps/parcelpanel'
}
